[package]
name = "nissy_f"
version = "0.0.0"
edition = "2021"
publish = false
description = "nissy_f"
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
