[package]
name = "nissy_b"
version = "0.0.2"
edition = "2021"
description = "nissy_b"
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nissy_a = { workspace = true }
