[package]
name = "nissy_d"
version = "0.0.1"
edition = "2021"
description = "nissy_d"
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nissy_b = { workspace = true }
nissy_c = { workspace = true }
