[package]
name = "nissy_a"
version = "0.0.3"
edition = "2021"
description = "nissy_a"
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
