[package]
name = "nissy_e"
version = "0.0.2"
edition = "2021"
description = "nissy_e"
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nissy_d = { workspace = true }
